import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [

  {
    path: "",
    title: "Examples",
    moduleName: "example",
    icon: "feather",
    class: "",
    groupTitle: false,
    submenu: [
      {
        path: "example/form",
        title: "FORM",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/simpleform",
        title: "SIMPLEFORM",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/table",
        title: "TABLE",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/accordion",
        title: "ACCORDION",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "dashboard/DashBoard",
        title: "DASHBOARD",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/tabForm",
        title: "TABBED FORM",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/editTable",
        title: "editTable",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/TreeView",
        title: "TreeView",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/DocketTable",
        title: "Drill Down",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/TableDailog",
        title: "TableDailog",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/AdvanceDashboard",
        title: "AdvanceDashboard",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/viewprint",
        title: "ViewPrint",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
      {
        path: "example/expandtable",
        title: "Expandable Table",
        moduleName: "example",
        icon: "",
        class: "",
        groupTitle: false,
        submenu: [],
      },
    ],
  },
];
